[Unit]
# This would normally be added automatically by the RuntimeDirectory=
# and StateDirectory= directives, but since this unit uses
# DefaultDependencies=no it is not.
RequiresMountsFor=/var/volatile
