[Unit]
# Yocto has its own mechanism for setting up an overlayfs for /var/lib and
# other writable directories on a read only rootfs.
# This unit sets DefaultDependencies=no, resulting with a race condition
# with this custom mechanism.
After=var-volatile-lib.service
