#@TYPE: Machine
#@NAME: NXP i.MX8MPlus FRDM
#@DESCRIPTION: Machine configuration for NXP i.MX8MPlus FRDM board

SOC_FAMILY = "mx8mp"
include conf/machine/include/soc-family.inc

DEFAULTTUNE = "cortexa53-crypto"
require conf/machine/include/arm/armv8a/tune-cortexa53.inc

PREFERRED_PROVIDER_virtual/bootloader ?= "barebox-reference"
REQUIRED_VERSION_barebox-reference = "2026.06.0"

PREFERRED_PROVIDER_virtual/kernel ?= "linux-reference"

#
# Barebox
#

BAREBOX_BINARY = "barebox-nxp-imx8mp-frdm-s.img"

#
# Linux
#

KERNEL_DEVICETREE = "freescale/imx8mp-frdm.dtb"
KERNEL_IMAGETYPE = "Image.gz"

INITRAMFS_FSTYPES = "cpio.zst"

DDR_FIRMWARE_FILES = " \
    lpddr4_pmu_train_1d_imem.bin \
    lpddr4_pmu_train_1d_dmem.bin \
    lpddr4_pmu_train_2d_imem.bin \
    lpddr4_pmu_train_2d_dmem.bin \
"

#
# Machine Features
#

MACHINE_FEATURES = "usbhost vfat serial rtc habv4"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " \
    kernel-modules \
"

# Do not include Linux kernel in the root filesystem
BAD_RECOMMENDATIONS = "kernel-image-*"
