DISTRO = "ave"
DISTRO_NAME = "AVE Linux"


# Copied from reference-BSP
DISTRO_VERSION = "6.0.99-0"

LOCALCONF_VERSION = "2"

# FIXME: Keep implicit defaults applied before
# https://git.openembedded.org/openembedded-core/commit/?id=159148f4de2595556fef6e8678578df83383857b
# See https://github.com/pengutronix/YOCTO.BSP-PTX-Reference/issues/164
DISTRO_FEATURES_DEFAULTS ?= "gobject-introspection-data ldconfig opengl multiarch wayland vulkan"
DISTRO_FEATURES = "ext2 ipv4 ipv6 minidebuginfo usbgadget usbhost wifi xattr vfat seccomp rauc"
DISTRO_FEATURES_OPTED_OUT += "ptest"

# Select systemd as init manager
INIT_MANAGER ?= "systemd"

# Let system trigger the HW watchdog.
# Services can safely use systemd-controlled software watchdogs.
# https://0pointer.de/blog/projects/watchdog.html
WATCHDOG_RUNTIME_SEC ?= "30"

# Set static uids/gids to allow migration and shared partitions
# between update slots.
USERADDEXTENSION = "useradd-staticids"
USERADD_ERROR_DYNAMIC = "error"
USERADD_UID_TABLES = "files/static-passwd"
USERADD_GID_TABLES = "files/static-group"

DISTRO_EXTRA_RDEPENDS += "packagegroup-core-boot"

# add build info file (/etc/build) to rootfs to ease traceability
INHERIT += "image-buildinfo"

# We don't use package feeds or on-target package management by default.
# Thus this QA check just produces unnecessary noise. Lower to warnings.
ERROR_QA:remove = "version-going-backwards"
WARN_QA:append = " version-going-backwards"

INHERIT += "uninative"

BB_SIGNATURE_HANDLER ?= "OEEquivHash"
BB_HASHSERVE ??= "auto"

# recommend ipk package management - make sure to comment or set it in local.conf.sample
PACKAGE_CLASSES ?= "package_ipk"
# gzip fast (-1) compression to save time and RAM
OPKGBUILDCMD ??= "opkg-build -Z gzip -a '-1nT'"
# faster XZ compression to save time and RAM (active since dunfell)
SDK_XZ_COMPRESSION_LEVEL = "-1"
# disable some unused LLVM targets (see llvm_git.bb)
# this reduces llvm-native:do_compile by ~8% (of ~6 CPU hours)
LLVM_TARGETS_TO_BUILD = "AArch64;ARM;BPF;RISCV;X86;${LLVM_TARGETS_GPU}"

# ave additions:

DISTRO_FEATURES += "pam"
DISTRO_FEATURES += "gtk"
