#!/usr/bin/env sh
# SPDX-License-Identifier: MIT
#
# Copyright Pengutronix <yocto@pengutronix.de>

verityrootfs_enabled() {
	return 0
}

verityrootfs_run() {
	if [ ! -e /verity-params ]; then
		# This should never happen since we always generate a verity rootfs
		fatal "verity-params doesn't exist"
	fi

	if [ -z "${bootparam_verity_root}" ]; then
		fatal "no verity_root= parameter given"
	fi

	msg "Waiting for dm-verity partition ${bootparam_verity_root}..."
	until [ -e "${bootparam_verity_root}" ]; do sleep 0.1; done

	msg "Loading verity parameters..."
	. /verity-params

	msg "verity root hash: $VERITY_ROOT_HASH"

	msg "Configuring verity device mapper target for ${bootparam_verity_root}..."
	dmsetup create verity -r --table "0 $VERITY_DATA_SECTORS verity 1 \
		${bootparam_verity_root} ${bootparam_verity_root} \
		$VERITY_DATA_BLOCK_SIZE $VERITY_HASH_BLOCK_SIZE \
		$VERITY_DATA_BLOCKS $VERITY_DATA_BLOCKS \
		$VERITY_HASH_ALGORITHM $VERITY_ROOT_HASH $VERITY_SALT \
		1 ignore_zero_blocks"

	msg "Mounting verity device mapper..."
	mount -o ro /dev/dm-0 $ROOTFS_DIR || fatal "Failed to mount rootfs!"
}
